version: "3.8"
services:
  base:
    build:
      context: .
      dockerfile: Dockerfile.base
    image: project-base

  cloud_broker:
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"

  fog_one_broker:
    image: eclipse-mosquitto:latest
    ports:
      - "1884:1883"

  fog_two_broker:
    image: eclipse-mosquitto:latest
    ports:
      - "1885:1883"

  cloud:
    build:
      context: .
      dockerfile: ./cloud/Dockerfile
    depends_on:
      - cloud_broker
    volumes:
      - ./data:/app/data

  edge:
    build:
      context: .
      dockerfile: ./edge/Dockerfile
    depends_on:
      - fog_one_broker
      - fog_two_broker

  twin:
    build:
      context: .
      dockerfile: ./fog/Dockerfile
    depends_on:
      - fog_one_broker
    environment:
      - ACTIVE_NODE=fog_one
    volumes:
      - ./data:/app/data