version: "3.8"

services:

  twin:
    image: project-twin:latest
    networks:
      - iot_net
    environment:
      - BROKER=tcp://192.168.1.217:1883
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.type == fog
      restart_policy:
        condition: any

  fog_home:
    image: project-fog:latest
    networks:
      - iot_net
    environment:
      - BROKER=tcp://192.168.1.217:1883
      - FOG_NODE=home
    deploy:
      placement:
        constraints:
          - node.labels.type == fog

  fog_work:
    image: project-fog:latest
    networks:
      - iot_net
    environment:
      - BROKER=tcp://192.168.1.217:1883
      - FOG_NODE=work
    deploy:
      placement:
        constraints:
          - node.labels.type == fog

  edge_home:
    image: project-edge:latest
    networks:
      - iot_net
    environment:
      - EDGE_TYPE=home
      - TOPIC=human/home
      - BROKER=tcp://192.168.1.217:1883

  edge_work:
    image: project-edge:latest
    networks:
      - iot_net
    environment:
      - EDGE_TYPE=work
      - TOPIC=human/work
      - BROKER=tcp://192.168.1.217:1883

networks:
  iot_net:
    driver: overlay