version: "3.8"
services:
  cloud_broker:
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"

  fog_one_broker:
    image: eclipse-mosquitto:latest
    ports:
      - "1884:1883"

  fog_two_broker:
    image: eclipse-mosquitto:latest
    ports:
      - "1885:1883"

  cloud:
    build:
      context: .
      dockerfile: ./cloud/Dockerfile
    depends_on:
      - cloud_broker
    volumes:
      - ./data:/app/data

  edge_home:
    build:
      context: .
      dockerfile: ./edge/Dockerfile
    environment:
      - EDGE_TYPE=home
      - TOPIC=human/home
    depends_on:
      - cloud_broker
      - fog_one_broker
      - fog_two_broker

  edge_mobile:
    build:
      context: .
      dockerfile: ./edge/Dockerfile
    environment:
      - EDGE_TYPE=mobile
      - TOPIC=human/mobile
    depends_on:
      - cloud_broker
      - fog_one_broker
      - fog_two_broker

  edge_work:
    build:
      context: .
      dockerfile: ./edge/Dockerfile
    environment:
      - EDGE_TYPE=work
      - TOPIC=human/work
    depends_on:
      - cloud_broker
      - fog_one_broker
      - fog_two_broker

  twin:
    build:
      context: .
      dockerfile: ./fog/Dockerfile
    depends_on:
      - fog_one_broker
    environment:
      - ACTIVE_NODE=fog_one
    volumes:
      - ./data:/app/data