FROM gcc:12
WORKDIR /app

RUN apt-get update && apt-get install -y \
    tzdata \
    cmake \
    git \
    libssl-dev \
    libpaho-mqtt-dev \
    libpaho-mqttpp-dev \
    nlohmann-json3-dev \
    && rm -rf /var/lib/apt/lists/*

ENV TZ=Europe/Stockholm